# -*- coding: utf-8 -*-
"""LR_1_task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tH7gKDF28BPALb0YQZikLG-pZ8wiYvKO
"""

import numpy as np
from sklearn import preprocessing

input_data = np.array([[5.1, -2.9, 3.3],
 [-1.2, 7.8, -6.1],
 [3.9, 0.4, 2.1],
 [7.3, -9.9, -4.5]])

print("--- Вхідні дані ---")
print(input_data)

# 2.1.1. Бінаризація даних
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\n--- Binarized data ---")
print(data_binarized)

# 2.1.2. Виключення середнього
print("\n--- BEFORE (Mean & Std) ---")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

data_scaled = preprocessing.scale(input_data)
print("\n--- AFTER (Mean & Std) ---")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

# 2.1.3. Масштабування MinMax
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\n--- Min max scaled data ---")
print(data_scaled_minmax)

# 2.1.4. Нормалізація (L1 та L2)
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')

print("\n--- l1 normalized data ---")
print(data_normalized_l1)
print("\n--- l2 normalized data ---")
print(data_normalized_l2)

input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']

# Створення кодувальника
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

# Виведення відображення слів на числа
print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)

# Перетворення випадкового набору міток
test_labels = ['green', 'red', 'black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))

# Декодування набору чисел
encoded_vals_to_decode = [3, 0, 4, 1]
decoded_list = encoder.inverse_transform(encoded_vals_to_decode)
print("\nEncoded values =", encoded_vals_to_decode)
print("Decoded labels =", list(decoded_list))

import numpy as np
from sklearn import preprocessing

# Значення для Варіант 1

# Значення змінної input_data для 1-го варіанта з Таблиці 1
input_data = np.array([
    [4.3, -9.9, -3.5],
    [-2.9, 4.1, 3.3],
    [-2.2, 8.8, -6.1],
    [3.9, 1.4, 2.2]
])

print("--- Нові вхідні дані (Варіант 1) ---")
print(input_data)

# 1. Бінаризація
threshold_value = 2.2
data_binarized = preprocessing.Binarizer(threshold=threshold_value).transform(input_data)
print("\n--- Binarized data (Поріг = 2.2) ---")
print(data_binarized)

# 2. Виключення середнього
print("\n--- BEFORE (Mean & Std) ---")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

data_scaled = preprocessing.scale(input_data)
print("\n--- AFTER (Mean & Std) ---")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

# 3. Масштабування MinMax
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\n--- Min max scaled data ---")
print(data_scaled_minmax)

# 4. Нормалізація
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')

print("\n--- l1 normalized data ---")
print(data_normalized_l1)
print("\n--- l2 normalized data ---")
print(data_normalized_l2)