# -*- coding: utf-8 -*-
"""LR_1_task_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tH7gKDF28BPALb0YQZikLG-pZ8wiYvKO
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from utilities import visualize_classifier

input_file = 'data_multivar_nb.txt'
data = np.loadtxt(input_file, delimiter=',')
X, y = data[:, :-1], data[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

classifier_svm = SVC(kernel='linear', random_state=3)
classifier_svm.fit(X_train, y_train)

y_test_pred = classifier_svm.predict(X_test)
accuracy = 100.0 * (y_test == y_test_pred).sum() / X_test.shape[0]
print(f"Accuracy of SVM classifier = {round(accuracy, 2)}%")

visualize_classifier(classifier_svm, X_test, y_test)